---
title: "IF36_TD_Shiny"
author: "Klimentiy Mirek"
date: "2025-05-28"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
head(starwars)
```

```{r eruptions, echo=FALSE}
library(shiny)
library(shinydashboard)
library(dplyr)
notes_map <- setNames(0:11, c("Do", "Do / Ré", "Ré", "Ré / Mi", "Mi", "Fa", 
           "Fa / Sol", "Sol", "Sol / La", "La", "La / Si", "Si"))
dataset <- read_csv('/Users/klim/Downloads/Spotify_Youtube.csv');
dataset_question_5 <- dataset %>% 
  filter(!is.na(Duration_ms)) %>%
  mutate(Duration_min = (Duration_ms / 1000)/60)
dataset_question_5_plot2 <- dataset_question_5 %>% filter(Duration_min < 10);


shinyApp(
  ui = dashboardPage(
    dashboardHeader(
      title = tags$div("Durée moyenne d'une chanson", style = "font-size: 12px;"),
      titleWidth = 200
    ),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Stats", tabName = "stats", icon = icon("calendar")),
        menuItem("Graphiques", tabName = "graphiques", icon = icon("signal")),
        selectInput("var", label = "La tonalité choisi", choices = list("Do","Do / Ré","Ré","Ré / Mi","Mi","Fa","Fa / Sol", "Sol","Sol / La","La","La / Si","Si"), selected = "Do")
      ),
      width = 200
    ),
    dashboardBody(
      fluidRow(
        # A static valueBox
        valueBoxOutput("valuebox1"),
        valueBoxOutput("valuebox"),
      ),
      # infoBoxes with fill=FALSE
      fluidRow(
        # A static infoBox
        infoBoxOutput("info1"),
        infoBoxOutput("info2")
      )
    ),
    skin = "green"
  ),
  server = function(input, output) {
    output$valuebox <- renderValueBox({
    valueBox(
      value = count(tonalite <- dataset %>% filter(Key == notes_map[input$var])),
      subtitle = "Nombre des elements choisis",
      icon = icon("list"),
      color = "red"
    )
  })
    
    output$valuebox1 <- renderValueBox({
    valueBox(
      value = input$var,
      subtitle = "Tonalité choisi",
      icon = icon("list"),
      color = "blue"
    )
  })
    
    output$info1 <- renderInfoBox({
      infoBox(
        title = "Durée moyenne d'une chanson (min)",
        value = dataset_question_5 %>% filter(Key == notes_map[input$var]) %>% summarise(mean_duration = round(mean(Duration_min, na.rm = TRUE), digits = 2)) %>% pull(mean_duration),
        icon = icon("hourglass"),
        color = "purple"
      )
    })
    
    output$info2 <- renderInfoBox({
      infoBox(
        title = "Pourcentage des valeurs utilisés",
        value = round(((count(tonalite <- dataset %>% filter(Key == notes_map[input$var]))) / count(tonalite <- dataset) * 100), digits = 2),
        icon = icon("percentage"),
        color = "black"
      )
    })
  }
)
```

```{r hello, echo=FALSE}
library(shiny)
library(shinydashboard)
library(ggplot2);
library(scales);
library(readr);
library(dplyr);
library(magrittr);
library(tidyr);
library(boot);
library(forcats);
library(fmsb);
library(tibble)


shinyApp(
  ui = dashboardPage(
    dashboardHeader(
      title = tags$div("Durée moyenne d'une chanson", style = "font-size: 12px;"),
      titleWidth = 200
    ),
    dashboardSidebar(
      sidebarMenu(
        menuItem("Stats", tabName = "stats", icon = icon("calendar")),
        menuItem("Graphiques", tabName = "graphiques", icon = icon("signal")),
        sliderInput("range", label = "Nb bins:", min = 1, max = 100, value = 10),
        selectInput("var", label = "La tonalité choisi", choices = list("Do","Do / Ré","Ré","Ré / Mi","Mi","Fa","Fa / Sol", "Sol","Sol / La","La","La / Si","Si"), selected = "Do")
      ),
      width = 200
    ),
    dashboardBody(
        box(
          title = "Repartition des chansons en fonction de la durée", status = "primary", solidHeader = TRUE,
          plotOutput("plot1", height = 250), 
          width = 400
        ),
    ),
    title = "Texas Housing",
    skin = "green"
  ),
  server <- function(input, output) {

  output$plot1 <- renderPlot({
    # Données filtrées selon la note choisie
    data_filtered <- dataset_question_5_plot2 %>%
      filter(Key == notes_map[[input$var]])

    # Calculs statistiques
    mean_val <- mean(data_filtered$Duration_min, na.rm = TRUE)
    sd_val <- sd(data_filtered$Duration_min, na.rm = TRUE)

    # Création du graphique
    ggplot(data_filtered, aes(x = Duration_min)) +
      geom_histogram(aes(y = ..density..),
                     bins = input$range,
                     fill = "#69b3a2",
                     color = "#e9ecef",
                     alpha = 0.9) +

      stat_function(fun = dnorm,
                    args = list(mean = mean_val, sd = sd_val),
                    aes(color = "Densité théorique"),
                    size = 1) +

      geom_vline(xintercept = mean_val,
                 color = "red",
                 linetype = "dashed",
                 size = 0.5) +

      scale_x_continuous(breaks = seq(0, 20, 1)) +
      labs(x = "Durée (en minutes)", y = "Fréquence") +
      scale_color_manual(name = "Légende",
                         values = c("Densité théorique" = "red")) +
      theme_minimal()
  })

}
)
```
